### ISSUE TITLE
fpOdf package can not be compiled with FPC 3.2 fixes

### ISSUE THREAD

**Issue by zeljkoavramovic** [dgaspary/fpOdf#1]
Fix to compile with FPC 3.2.x:

Open odf_types.pas and replace all instances of ": T)" with ": TElementType)" (all without quotes).

**Comment by dgaspary** [comment]
I Applied your suggestion. I have some updates to commit, and planned improvement to the project, but I am without time left at the moment. I hope this update helps.

Thank you.

**Comment by zeljkoavramovic** [comment]
Thank you!
