### ISSUE TITLE
fpODF can not compile on FPC 3.0.4 and FPC trunk

### ISSUE THREAD

**Issue by zeljkoavramovic** [dgaspary/fpOdf#2]
It seam that putting lazfileutils to uses section fixes the problem - needs further testing:
https://forum.lazarus.freepascal.org/index.php/topic,34297.msg310920.html#msg310920

Please make the corrections so your latest package can work with OPM.

Thanks!

**Comment by dgaspary** [comment]
Done (not tested).

Thank you.

**Comment by zeljkoavramovic** [comment]
Thanks!
