### ISSUE TITLE
proposed fix for HelloWorld example to work on Windows

### ISSUE THREAD

**Issue by zeljkoavramovic** [dgaspary/fpOdf#3]
In OdtHelloWorld.lpr line

    cOutput = '/tmp/HelloWorld.odt';

needs to be changed with something like this:

    {$IF defined(WINDOWS)}
    cOutput = 'HelloWorld.odt';
    {$ELSE}
    cOutput = '/tmp/HelloWorld.odt';
    {$ENDIF}

**Comment by dgaspary** [comment]
Done. Thank You.
