### ISSUE TITLE
Set image in ODF file

### ISSUE THREAD

**Issue by FlechitUp** [dgaspary/fpOdf#6]
Hi, 
I'm developing a project for the university and I'm really interested in your code. I would like to add an image in ODF file, I tried to create a lot of functions, but I had troubles. Could you help me please ? Maybe with an example. 
Thanks in advance

**Comment by dgaspary** [comment]
Hi
> I'm developing a project for the university and I'm really interested in your code.

Nice to know. 

> I would like to add an image in ODF file, I tried to create a lot of functions, but I had troubles. 
> Could you help me please ? Maybe with an example.

I never tried it before. 

But I included a picture using libreoffice, looking inside, that is what it generated:

<text:p text:style-name="P1">
   <draw:frame draw:style-name="fr1" draw:name="Image1" text:anchor-type="paragraph" svg:width="5.8055in" svg:height="3.6571in" draw:z-index="0">
      <draw:image>
         <office:binary-data>

        "IMAGE DATA HERE"

         </office:binary-data>
      </draw:image>
   </draw:frame>      
</text:p text:style-name="P1">

On "IMAGE DATA HERE" it seems to be image data encoded with MIME.

So... it's not that hard (when we know how can be done). 

Did you try something like that?

**Comment by dgaspary** [comment]
The editor here removed the tag signs of
draw:image and office:binary-data.

**Comment by dgaspary** [comment]
I included an "ImageInsert" example .

**Comment by FlechitUp** [comment]
Thank you so much :dancer:
