### ISSUE TITLE
Insert Tables

### ISSUE THREAD

**Issue by AndreRamosDroidex** [dgaspary/fpOdf#7]
Hi Bro, I like your work, Im trying to change from fpvectorial to your implementation, its for a university homework.

So ,how do you insert tables? thanks.

**Comment by dgaspary** [comment]
On Thu, Nov 21, 2019 at 1:09 PM Andre1996 <notifications@github.com> wrote:

> Hi Bro, I like your work, Im trying to change from fpvectorial to your
> implementation, its for a university homework.
>

Hi. Happy to read that, hope it can help you.


> So ,how do you insert tables? thanks.
>
My TLDR; response would be: Today, is not possible to do that.

By that I mean.. is possible if you know how tables work in an ODF file,
and repeat the steps one by one.

Looking at code of a basic ODT file with tables.. it seems simple to do.

I believe I can manage to implement it tomorrow, maybe saturday.

But It's not a promise and I talking about simple tables. With uniform
cells and rows sizes.

**Comment by AndreRamosDroidex** [comment]
Thank you, 

I have another question, do you how to add styles to cells, it's on the same way?

thanks in advance, again.

**Comment by dgaspary** [comment]
On Thu, Nov 21, 2019 at 1:50 PM Andre1996 <notifications@github.com> wrote:

> I have another question, do you how to add styles to cells, it's on the
> same way?


I just know the basics, how to make the text bold, because this is a change
to the text instead of the cell.

But, I can try to discover.. Can you be more specific? What do you have in
mind, what kind of change of style?

**Comment by dgaspary** [comment]
I posted the "Table Insert" Example.

The main difficulty is to know the styles necessary. As soon as possible, I will try to implement that within the main fpOdf code.

**Comment by AndreRamosDroidex** [comment]
Thanks bro, I meant border style (like border colors, font styles) or cell color.

I appreciate your help.

**Comment by AndreRamosDroidex** [comment]
Hi, one question, is it possible to concatenate two files .odt?  do you have a simple example? thank you man.

**Comment by dgaspary** [comment]
> Thanks bro, I meant border style (like border colors, font styles) or cell color.

A style with green background cell blooks like the excerpt  bellow:

 `  <style:style style:name="Table1.B2" style:family="table-cell">
        <style:table-cell-properties fo:background-color="#00cc00" fo:padding="0.0382in" fo:border-left="0.05pt solid #000000" fo:border-right="none" fo:border-top="none" fo:border-bottom="0.05pt solid #000000" />
  </style:style>`

You could take one style from CreateStyles procedure at example I posted and modify it to generate code like above.

**Comment by dgaspary** [comment]
> Hi, one question, is it possible to concatenate two files .odt? do you have a simple example? 
> thank you man.

I believe you could copy the elements from one file, add to the other . 

Do the same with styles, taking care to not duplicate names, renaming and referencing when necessary.

Sorry but to this kind of operation is only possible (currently) if you operate at XML level.

**Comment by AndreRamosDroidex** [comment]
Thanks bro, i hope I'm not disturbing you too much.

It's just that I like to learn . so:

I generate tables with styles but with the FPSpreadsheet library, then. Could you use the generated TStringstream and put it in your implementation?

thank you.

**Comment by dgaspary** [comment]
On Mon, Nov 25, 2019 at 11:22 AM Andre1996 <notifications@github.com> wrote:

> Thanks bro, i hope I'm not disturbing you too much.
>
No problem, I am glad to help. Just have time restrictions, not always I
can.


> I generate tables with styles but with the FPSpreadsheet library, then.
> Could you use the generated TStringstream and put it in your implementation?
>
Maybe.. The problem is.. The "Styles" part needs a good amount of
work-hours... Not only for tables.

I have no short time plans for it. Maybe until the end of January, I don't
know.

Better you don't expect it so soon if it can interfere with your university
work.
